### ISSUE TITLE
Feature request: Contactless payment

### ISSUE THREAD

**Issue by mathisfo** [dotkom/mysterious-powerking-conspiracy#12]
This would allow for purchase with mastercard (im broke and need pk) or Apple Pay

**Comment by FredrikAugust** [comment]
This is only partially a nibble feature as it would also require quite some work in OW. It's been brought up more times than I can count though, so I'll see if I can't get an answer soon.

**Comment by FredrikAugust** [comment]
EDIT: Sorry, this won't work.

**Comment by Aborysa** [comment]
@mathisfo you can already add saldo to your account on https://online.ntnu.no/profile/saldo using a mastercards.
