### ISSUE TITLE
"Kunne ikke logge deg inn" loop if no response from OW

### ISSUE THREAD

**Issue by FluidSense** [dotkom/mysterious-powerking-conspiracy#23]
If you try to log in on Nibble while OW is down, the error messages will keep on being generated until someone try to log in when OW is back up.

How to replicate:
 - Disconnect from OW somehow.
 - Try to log in.
 - See a waterfall of error messages.
 - Connect to OW somehow.
 - See error messages stop after someone try to log in.

**Comment by FredrikAugust** [comment]
This has been fixed, but the new version is not pulled to the computer at the office.

**Comment by FredrikAugust** [comment]
https://github.com/dotkom/mysterious-powerking-conspiracy/commit/c8a9057f5a7ded2d5f21d8e8f8f495f7f1dc9c1c

**Comment by FredrikAugust** [comment]
It sadly needs to be merged with master first, before being good to go, but that shouldn't be difficult.
