### ISSUE TITLE
Sort items based on personal purchase history 

### ISSUE THREAD

**Issue by aslakhol** [dotkom/mysterious-powerking-conspiracy#3]
I would like the products screen to be sorted by my personal purchase history. Perhaps the default tab could be sorted in this manner and other tabs are sorted by some other matter.

**Comment by FredrikAugust** [comment]
I think I'll only have one tab in the new nibble, as I don't see the point of more than one if the interface is structured logically. 

I'll merge this issue with #4 and continue the discussion there.
