### ISSUE TITLE
Filter out discontinued items in the dashboard inventory

### ISSUE THREAD

**Issue by kattn** [dotkom/mysterious-powerking-conspiracy#8]
The current solution is to manually add a [Discontinued] text to each discontinued item so it can be sorted away by name/ignored. A filter on what items are currently sold would be much better.

**Comment by FredrikAugust** [comment]
This should 10000000% be a boolean field in OW that should be used for filtering out discontinued items when nibble requests what items are up for purchase.

I guess I could hickety-hack this by adding a quick

```javascript
if (/^.+\[Discontinued\]$/.test(item.name)) {
    // begone ~thot~ item
}
```

but I think the OW solution is
- cleaner
- cooler
- less work for me
- more work for everyone else
- web scale
- sounds cooler

So unless anyone protests, I'll see if I can't get someone to implement this.
